# Generated by Django 3.1.5 on 2021-02-06 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('f_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('l_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('organization', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('zip_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('career_profile', models.TextField(blank=True)),
                ('send_email', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plats_bank.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('between', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Erfarenheter',
                'verbose_name_plural': 'Erfarenheter',
            },
        ),
        migrations.CreateModel(
            name='Employments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('place', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('between', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anställningar',
                'verbose_name_plural': 'Anställningar',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='employment',
            field=models.ManyToManyField(blank=True, to='accounts.Employments'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='experience',
            field=models.ManyToManyField(blank=True, to='accounts.Experiences'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='jobb_type',
            field=models.ManyToManyField(blank=True, to='plats_bank.Job_type'),
        ),
    ]
