# Generated by Django 3.1.5 on 2021-02-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Namn')),
                ('slug', models.CharField(blank=True, max_length=50)),
                ('lau_2_code_2015', models.CharField(max_length=6, unique=True, verbose_name='Municipality codes')),
            ],
            options={
                'verbose_name': 'post ort',
                'verbose_name_plural': 'post orts',
            },
        ),
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Arbets yrken')),
                ('af_id', models.CharField(max_length=30, unique=True, verbose_name='AF code')),
                ('definition', models.TextField(blank=True, verbose_name='Beskrivning')),
                ('ssyk_code_2012', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Arbets yrken',
                'verbose_name_plural': 'Arbets yrken',
            },
        ),
        migrations.CreateModel(
            name='Job_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('af_id', models.IntegerField(unique=True)),
                ('application_deadline', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ad_url', models.URLField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats_bank.city', verbose_name='Arbets ort')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats_bank.job_type', verbose_name='Yrke')),
            ],
            options={
                'verbose_name': 'Jobb annons',
                'verbose_name_plural': 'Jobb annonser',
            },
        ),
    ]
